name: Problem Report
description: please report any technical issue with this home assistant integration - please note this is not a official evcc repository or service
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Issue with `chargerPhases1p3p` is already fixed! - Update your integration via HACS to get the latest version!
        1. In Home Assistant go to `HACS`
        2. In the list of installed integrations search for `evcc`
        3. Click on the 3-dot menu on the right side of the `evcc` integration list entry
        4. Click on `Update Information`
        5. Note now that a new version is available
        6. Install the update
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please go though this short checklist - TIA
      options:
        - label: I confirm, that I my evcc instance is configured, is up & running and that **I can access the default evcc webinterface**
          required: true
        - label: My home assistant version is up to date.
          required: true
        - label: I am using the **latest** version of the integration | See the [release list @github](https://github.com/marq24/ha-evcc/releases) or in home assistant use the HACS 'Update Information' function to ensure that the **latest** released version of the integration is installed. This HACS function can be accessed via the 3-dot menu on the right side for each integration in the HACS integration list.
          required: true
        - label: I have [checked all issues (incl. the closed ones)](https://github.com/marq24/ha-evcc/issues?q=is%3Aissue+is%3Aclosed) for similar issues in order to avoid reporting a duplicate issue .
          required: true
        - label: I have prepared DEBUG log output (for technical issues) | In most of the cases of a technical error/issue I would have the need to ask for DEBUG log output of the integration. There is a short [tutorial/guide 'How to provide DEBUG log' here](https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md)
          required: true
        - label: I confirm it's really an issue | In the case that you want to understand the functionality of a certain feature/sensor Please be so kind and make use if the discussion feature of this repo (and do not create an issue) - TIA
        - label: I confirm, that I did not read any of the previous bulletin-points and just checked them all, since I don't wanted to waste my time with the details like reading or follow any of the existing hints and instructions. Instead, I prefer that the maintainer of this repro should spend time explaining the things to me, that I have previously ignored all the time. It's the maintainers fault, that they provide open source software and willing to offer support for free.
  - type: textarea
    id: content
    attributes:
      label: Add a description
      placeholder: "Please provide details about your issue - in the best case a short step by step instruction how to reproduce the issue - TIA."
  - type: textarea
    id: logs
    attributes:
      label: Add your DEBUG log output
      placeholder: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: shell